import { IList } from "./types";

const list: IList[] = [
    {name: 'San Francisco'},
    {name: 'Hamburg'},
    {name: 'New Delhi'},
    {name: 'Bristol'},
    {name: 'Manchester'},
    {name: 'Edinburgh'},
    {name: 'Philadelphia'},
    {name: 'Madrid'},
    {name: 'Leeds'},
    {name: 'Berlin'},
    {name: 'Buenos Aires'},
    {name: 'Barcelona'},
    {name: 'Hong Kong'},
    {name: 'Honolulu'},
    {name: 'Long Beach'},
    {name: 'Amsterdam'},
    {name: 'Dongguan'},
    {name: 'Munich'},
    {name: 'Albuquerque'},
    {name: 'Santiago'},
    {name: 'Milwaukee'},
    {name: 'Riyadh'},
    {name: 'Oxford'},
    {name: 'Brussels'},
    {name: 'Cambridge'},
    {name: 'Dallas'},
    {name: 'Dhaka'},
    {name: 'Sheffield'},
    {name: 'Phoenix'},
    {name: 'Glasgow'},
    {name: 'Damascus'},
    {name: 'Auckland'},
    {name: 'Charlotte'},
    {name: 'Bogotá'},
    {name: 'Toronto'},
    {name: 'Cologne'},
    {name: 'Shenzhen'},
    {name: 'Tianjin'},
    {name: 'San Antonio'},
    {name: 'Kolkata'},
    {name: 'Cairo'},
    {name: 'Athens'},
    {name: 'Denver'},
    {name: 'London'},
    {name: 'Guangzhou'},
    {name: 'Paris'},
    {name: 'Austin'},
    {name: 'Mexico City'},
    {name: 'Omaha'},
    {name: 'Perth'},
    {name: 'Seoul'},
    {name: 'Wichita'},
    {name: 'Birmingham'},
    {name: 'Ankara'},
    {name: 'Tucson'},
    {name: 'Colorado Springs'},
    {name: 'Boston'},
    {name: 'Kinshasa'},
    {name: 'Rio de Janeiro'},
    {name: 'New York'},
    {name: 'Las Vegas'},
    {name: 'São Paulo'},
    {name: 'New Orleans'},
    {name: 'Istanbul'},
    {name: 'Karachi'},
    {name: 'Kansas City'},
    {name: 'Bangkok'},
    {name: 'Tokyo'},
    {name: 'Miami'},
    {name: 'Louisville'},
    {name: 'San Jose'},
    {name: 'Birmingham'},
    {name: 'Atlanta'},
    {name: 'Dublin'},
    {name: 'Lima'},
    {name: 'Osaka'},
    {name: 'Rome'},
    {name: 'Boise'},
    {name: 'Santa Cruz'},
    {name: 'Houston'},
    {name: 'Sydney'},
    {name: 'Washington DC'},
    {name: 'Milan'},
    {name: 'Richmond'},
    {name: 'Dubai'},
    {name: 'Chicago'},
    {name: 'Ho Chi Minh City'},
    {name: 'Jacksonville'},
    {name: 'Virginia Beach'},
    {name: 'Little Rock'},
    {name: 'Mumbai'},
    {name: 'Wilmington'},
    {name: 'Pyongyang'},
    {name: 'Tehrān'},
    {name: 'Baltimore'},
    {name: 'Beijing'},
    {name: 'Budapest'},
    {name: 'Indianapolis'},
    {name: 'Santorini'},
    {name: 'Seattle'},
    {name: 'Lagos'},
    {name: 'Bucharest'},
    {name: 'San Diego'},
    {name: 'Sacramento'},
    {name: 'Liverpool'},
    {name: 'Los Angeles'},
    {name: 'Mesa'},
    {name: 'Torino'},
    {name: 'Shanghai'},
    {name: 'Fresno'},
    {name: 'Brisbane'},
    {name: 'Columbus'},
    {name: 'Montréal'},
    {name: 'Addis Ababa'},
    {name: 'Melbourne'},
    {name: 'Prague'},
    {name: 'Exeter'},
    {name: 'Detroit'},
    {name: 'Bradford'},
    {name: 'Yokohama'},
    {name: 'Singapore'},
    {name: 'Casablanca'},
    {name: 'Oklahoma City'},
    {name: 'Toulouse'},
    {name: 'Bangalore'},
    {name: 'Moscow'},
    {name: 'Vancouver'},
    {name: 'Baghdad'},
    {name: 'Nairobi'},
    {name: 'Vienna'},
    {name: 'Fort Worth'},
    {name: 'Bridgeport'},
    {name: 'Anchorage'},
    {name: 'Nashville'},
    {name: 'Warsaw'},
    {name: 'Memphis'},
    {name: 'Jakarta'},
    {name: 'Hyderabad'},
    {name: 'Belfast'},
    {name: 'Copenhagen'},
    {name: 'Zagreb'},
    {name: 'Portland'},
    {name: 'Stockholm'},
    {name: 'Wakefield'},
    {name: 'Calgary'},
    {name: 'Nice'},
    {name: 'Adelaide'},
    {name: 'Naples'},
    {name: 'Cardiff'},
    {name: 'Fargo'},
    {name: 'Wuhan'},
    {name: 'Kiev'},
    {name: 'Cheyenne'},
    {name: 'Oslo'},
    {name: 'Lille'},
    {name: 'Marseille'},
    {name: 'Manila'},
    {name: 'Bordeaux'},
    {name: 'Ahmedabad'},
    {name: 'Sendai'},
    {name: 'Lahore'},
    {name: 'Edmonton'},
    {name: 'Lyon'},
    {name: 'Maracaibo'},
    {name: 'Johannesburg'},
    {name: 'Caracas'},
    {name: 'Bremen'},
    {name: 'Stoke-on-Trent'},
    {name: 'St Petersburg'},
    {name: 'İzmir'},
    {name: 'Charleston'},
    {name: 'Santander'},
    {name: 'Raleigh'},
    {name: 'Sofia'},
    {name: 'El Paso'},
    {name: 'Brasília'},
    {name: 'Salvador'},
]
    export default list;